info:
  name: teambuilting-core

  description: Team Builting Core Service, microservice to store common configuration for the application
---

# Queue configuration
messaging:
  amqp:
    team:
      exchange:
        name: TEAMBUILTING.E.TEAM
        durable: true
        autodelete: false
    player:
      exchange:
        name: TEAMBUILTING.E.PLAYER
        durable: true
        autodelete: false

google:
  api:
    key: ${GOOGLE_API_KEY:AIzaSyAJP4-9qXXF8h9bhp57IxGnlM9e6Tl5CHA}

---

spring:
  profiles: production
  rabbitmq:
      host: ${RABBITMQ_HOST:localhost}
      virtual-host: ${RABBITMQ_VIRTUAL_HOST}
      username: ${RABBITMQ_USERNAME:guest}
      password: ${RABBITMQ_PASSWORD:guest}

---

endpoints:
  enabled: true # Enable endpoints.
  actuator.enabled: true # Enable the endpoint.

---

auth0:
  domain: manuelarte.eu.auth0.com
  issuer: https://manuelarte.eu.auth0.com/
  clientId: XOBz4RdzWoMnpxAvXKtK9R8W9IODYKsl
  clientSecret: tvKvKZd1tigVIAGztcOELwKIj0B0DswEbLdRG1PWu7NfZXk6VGbGkWdQjFpTZmWp
  securedRoute: NOT_USED
  base64EncodedSecret: true
  authorityStrategy: ROLES
  defaultAuth0ApiSecurityEnabled: false
  signingAlgorithm: HS256
  #signingAlgorithm: RS256
  #publicKeyPath: certificate/cert.pem